spring:
  application:
    name: audition-api
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
  sleuth:
    sampler:
      probability: 1.0
#  security:
#    user:
#      name: "admin"
#      password: "secret"
#    ignored: "/**"
server:
  max-http-request-header-size: 16KB
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "health,info" #TODO enable only info and health for security purposes. Consider that we may want to still access other actuator endpoints securely.

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

app:
  config:
    connectTimeout: 5000
    readTimeout: 3000
    auditionBaseUri: "https://jsonplaceholder.typicode.com"
    auditionPostsSuffix: "/posts/"
    auditionCommentsSuffix: "/comments"
    auditionCommentsFilter: "postId"
    auditionUserIdFilter: "userId"
    auditionTitleFilter: "title"

resilience4j:
  circuitbreaker:
    instances:
      backend:
        base-config: shared
    configs:
      shared:
        sliding-window-type: "count_based"
        register-health-indicator: true
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: "10s"
        wait-duration-in-open-state: "10s"
        slow-call-duration-threshold: "2s"
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
